### ISSUE TITLE
Maven deployment

### ISSUE THREAD

**Issue by tischi** [embl-cba/metaimage-io#2]
Hi @imagejan,

Could you please help me by having a look why this artifact was not deployed to our maven repository. I feel I am missing some step but I don't know which one...

**Comment by imagejan** [comment]
I guess the enforcer would have told you if you didn't always disable it 😉

As far as I can quickly grasp, your `pom.xml` is lacking several required fields, in particular `<ciManagement>`.

Did you run `github-actionify.sh` on this repository yet? From https://github.com/embl-cba/metaimage-io/commit/c179b58d445f6f8f05db64eb08e0ee725d7b144b it seems you tried to add/copy these files manually?

Some recommendations:
* **Never** have `<enforcer.skip>true</enforcer.skip>` in your `pom.xml`. Better fix the issues that make the enforcer fail.
* **Never** have `<scijava.app.directory>[...]</scijava.app.directory>` in your `pom.xml`. Define the directory in your local `.m2/settings.xml` so that maven picks them up, but they have nothing to do in your public source code.
* Use the tooling provided by SciJava (i.e. `github-actionify.sh` and `release-version.sh`) instead of copying boilerplate from existing repos.

**Comment by tischi** [comment]
Thanks a lot @imagejan ❤️ 
Thanks to your suggestions it works now!
